### ISSUE TITLE
Error when build images

### ISSUE THREAD

**Issue by bruttozz** [dataverse-broker/dataverse-broker#40] opened 2018-04-22 15:01 UTC
When I was ready to test our dataverse-broker with the authentication function locally, I met an error when run 'make deploy-openshift' in the terminal:

'''
HONGTAOs-MacBook-Pro:dataverse-broker brutto$ make deploy-openshift
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
	go build -o dataverse-broker-linux --ldflags="-s" github.com/dataverse-broker/dataverse-broker/cmd/dataverse-broker
fatal: Not a git repository (or any of the parent directories): .git
cp dataverse-broker-linux image/dataverse-broker
docker build image/ -t "quay.io/dataverse-broker/dataverse-broker:"
invalid argument "quay.io/dataverse-broker/dataverse-broker:" for t: invalid reference format
See 'docker build --help'.
make: *** [image] Error 125
'''

I tried relaunch oc and docker even restarted my mac, but the error still here. The version of dataverse-broker is the one under the master branch.

I also tried Paul's osb-starter-pack that way, deployed perfectly.

@SamiSousa said there was no error when he deployed the dataverse-broker on his laptop, I searched but there seems no one came up with this issue.

**Comment by SamiSousa** [comment] 2018-04-22 19:04
I'll look into these issues. Admittedly, my testing and development environment is limited. I've only tested the dataverse-broker on Ubuntu 16.04 LTS, and haven't had the chance to test for MacOS. My suggestion for now would be to setup an environment similar to mine:
- Ubuntu 16.04 LTS virtual machine (1 core, 2 GB RAM, although that's up to you)
- OpenShift 3.7.1
- Docker 18.03.0-ce
- Go 1.9.4

I'm aware that this setup might be a bit out of date, but I've gotten things to where it is now using this setup. I can help debug once you've set up this environment.

**Comment by SamiSousa** [comment] 2018-04-23 05:29
Updating to say that I've tested the broker on OpenShift 3.9.0 and things work fine, and the newer version is recommended.

**Comment by SamiSousa** [comment] 2018-04-24 00:03
Seems like the issue is gone, closing.

**Closed by SamiSousa** 2018-04-24 00:03 UTC
